FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /ducto-orchestrator-cloudrun ./cmd/ducto-orchestrator-cloudrun

FROM gcr.io/distroless/static-debian11
COPY --from=builder /ducto-orchestrator-cloudrun /ducto-orchestrator-cloudrun
ENTRYPOINT ["/ducto-orchestrator-cloudrun"]