# NOTE: A copy of this example is hosted at:
# > gs://ducto-public/02-gcs_config.yaml

# For GCS, we use a GCS URI for the program
program_file: gs://ducto-public/02-gcs_program.json

# Or, we can define the program inline for convenience
#program:
#  version: 1
#  instructions: []

source:
  type: http
  config:
    meta_field: _http
    use_env: true # Awareness of Cloud Run's `PORT` env for addr binding

output:
  type: stdout
  config:
    pretty: true
