name: CI

on:
  push:
    branches:
    - 'main'
    - 'dev'
    - 'feature/**'
  pull_request:
    branches:
    - 'main'
    - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Install Linter
        run: make lint-install

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'beta,pubsub-emulator'

      # Start the pub/sub emulator on a background job
      # 5-sec sleep is to give the emulator time to boot before continuing
      - name: Start Pub/Sub Emulator
        run: |
          gcloud config set project "$GOOGLE_CLOUD_PROJECT"
          gcloud beta emulators pubsub start --host-port=localhost:8085 &
          sleep 5
        env:
          GOOGLE_CLOUD_PROJECT: test-project

      # For GCS Unit Tests
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'testsandbox-3cb3f'
          credentials_json: ${{ secrets.GOOGLE_GCP_CREDENTIALS }}

      - name: Makefile CI
        run: make ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./docs/coverage.out
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true

      - name: Upload Coverage as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: docs/coverage.out

      - name: Deploy Coverage HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          allow_empty_commit: false

  # Docker ~> Google Cloud Run
  build-cloudrun-image:
    needs: ['build']
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with: {go-version: '1.24'}
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - uses: google-github-actions/auth@v2
        with:
          project_id: 'testsandbox-3cb3f'
          credentials_json: ${{ secrets.GOOGLE_GCP_CREDENTIALS }}

      - name: Build and push Cloud Run image
        run: |
          gcloud auth configure-docker ${{ env.REPO_DOMAIN }}
          docker build -f Dockerfile.cloudrun -t ${{ env.REPO }}:${{ github.run_number }} .
          docker tag ${{ env.REPO }}:${{ github.run_number }} ${{ env.REPO }}:latest
          docker push ${{ env.REPO }}:${{ github.run_number }}
          docker push ${{ env.REPO }}:latest
        env:
          REPO_DOMAIN: europe-west2-docker.pkg.dev
          REPO: europe-west2-docker.pkg.dev/testsandbox-3cb3f/ducto-docker/ducto-orchestrator-cloudrun
